name: ch01 hong
on:
  push:
    branches: [ch01-workflow]
jobs:
  build:
    runs-on: ubuntu-latest
    step:
      - run: echo xin chao
  deploy:
    needs: biuld
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.pull_request.title }}
      - uses: actions/setup-node@v7
        with:
          node-version: 18.20
