name: ch03 if off
on:
  push:
    branches: [ch03-bieu-thuc]
    paths: ['.github/workflows/ch03-if-off.yml']
permissions:
  contents: read
jobs:
  thu:
    runs-on: ubuntu-24.04
    steps:
      - name: "truoc"
        run: echo truoc
      - name: "if: off"
        if: off
        run: echo chay
