name: ch12-if-chuoi
on:
  push:
    branches: [ch12-tai-su-dung]
    paths: ['.github/workflows/ch12-if-chuoi.yml', '.github/actions/ch12-if-chuoi/**']
  workflow_dispatch:
permissions:
  contents: read
jobs:
  do:
    strategy:
      matrix:
        co: ['false', 'true']
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/ch12-if-chuoi
        with:
          co: ${{ matrix.co }}
